### ISSUE TITLE
created_at timestamp is updated for a deck sync

### ISSUE THREAD

**Issue by StuAtKong** [Kong/deck#180]
When using deck sync to make some changes in an existing route, after the sync the created_at field and updated_at fields in database are both set to the sync time. It is expected that any update to the existing route should change only the updated_at timestamp and not the created_at timestamp

Steps to Reproduce:

1. Create a service and route in kong with routing by header
2. Execute deck dump
3. Edit the kong.yaml file to change the custom header value in route
4 . Execute deck diff to check the changes
5. Execute deck sync
6. Check the database and the timestamps for created_at and updated_at fields which have both been updated

**Comment by hbagdi** [comment]
This is the case because decK uses PUT requests to update entities in Kong.
We won't be able to fix this problem.

**Comment by mmorel-35** [comment]
What if the PATCH verb was used instead of PUT, would it be helpful?

**Comment by hbagdi** [comment]
PATCH is intentionally not used because it changes the state of entities in unexpected ways at times. PUT is an overwrite in Kong which is a lot safer. We did have reports with problems around PATCH and hence rewrote part of codebase to instead use PUT at all times.
What problem is a newer created_at timestamp creating?

**Comment by andrerfneves** [comment]
I know this issue is closed, and I've read the comments and agree with the PUT approach. We'll live with this issue fine. For us the main pain point is when we wish to run a `deck diff/sync` we receive info like this:

<img width="273" alt="Screen Shot 2020-10-27 at 11 35 49 PM" src="https://user-images.githubusercontent.com/2574011/97387849-28ed9600-18ad-11eb-951b-c4c1f544cf64.png">

Now I understand it's updating all of the created_at`s, but when there are actual changes/updates to be made to any records, it'll be mixed in with the created_at updates. Deletion and creation of records is clear. Updates not so much. I understand it's a limitation, just wanted to exemplify the issue.

Cheers
