### ISSUE TITLE
deck diff is showing difference for default values

### ISSUE THREAD

**Issue by yewals** [Kong/deck#196]
Hi, We are using the Deck tool for Kong and we are getting an issue for deck diff. After using deck sync to import kong.yaml , when we do deck diff, it shows the difference for default values like 
```

   "config": {
-    "allowed_content_types": [
-      "application/json"
-    ],

-    "verbose_response": false,

-  "protocols": [
-    "grpc",
-    "grpcs",
-    "http",
-    "https"
-  ],

-  "created_at": 1.596559272e+09,
```

This is causing updating all services/routes in Kong. 
Versions used: Deck 1.1.0 and kong enterprise version: 1.5

**Comment by hbagdi** [comment]
This is a known limitation currently.
The current way to solve this problem is to configure your kong once, then do a `deck dump`, use the resulting configuration file to maintain your kong's configuration.
#89 was meant for some other things but can be re-used to solve this problem.

**Comment by yewals** [comment]
@hbagdi  Thanks for replying. Unfortunately, It will be difficult to use the configuration file generated by the deck dump. Since we have a large no of endpoints to be maintained in Kong, we are using an openapi2kong tool to generate kong.yaml file. Can you guide us on how to use the reference feature, I see it is still in an open state.

**Comment by hbagdi** [comment]
> Can you guide us on how to use the reference feature, I see it is still in an open state.

The feature is not yet implemented. There is no workaround for this problem other than the one I mentioned above.

**Comment by waciii-ra** [comment]
> 
> The feature is not yet implemented. There is no workaround for this problem other than the one I mentioned above.

@hbagdi 
I'm curious if you might explain why some default values don't need to be specified and others do.  I was exploring this and found as follows (for example):

**Services Configuration (NOT Required):**  `connect_timeout`, `read_timeout`, `write_timeout` 
**Services Configuration (Required):**  `retries`

**Routes Configuration (NOT Required):**  `preserve_host`, `regex_priority`
**Routes Configuration (Required):**  `http_redirect_status_code`, `path_handling`

**Comment by aaronhmiller** [comment]
@yewals can you perhaps apply tags? 

`      - tags:
          - OAS3_import`

as for leveraging openapi2kong, please have a look here: https://support.insomnia.rest/article/114-cli-generate-config

**Comment by rexcatus** [comment]
Is there a fix planned? If yes, is there an ETA on it? Following the work-around would complicate configuration as code, since the templates have to store all the default values. Also when upgrading to a newer version of Kong or of decK and new properties with default values are introduced, all templates will have to be updated so that deck does not report there are differences between the state file and the upgraded version Additionally, since if using templates to generate the state files,  and using different versions of Kong, adding these properties is not backwards compatible.

**Comment by rainest** [comment]
Re @waciii-ra's comment:

> I'm curious if you might explain why some default values don't need to be specified and others do. I was exploring this and found as follows

I haven't reviewed this in its entirety, but it looks like these come from https://github.com/Kong/deck/blob/v1.5.0/utils/constants.go

That enumerates some specific default values, but it's not exhaustive.

**Comment by hbagdi** [comment]
Some notes here:
- The first step here is to perform an audit of new fields and enable defaulting for them.
- We need to look at reports from customer and see if they complain about defaults not being populated for plugin configurations. If so, then we need to implemented defaulting logic for plugin configuration, which has a higher implementation cost and an even higher maintenance cost given Kong's roadmap around multi-language plugins. We should avoid investing in this area as much as possible.
- Boolean fields which default to `true` are incompatible with the defaulting logic in decK because of limitations in the Go language. There are workarounds but cost vs outcome has never made sense in the past.
- Finally, the solution that will have the highest ROI is #89 which makes it possible to programmatically override the values inside `utils/constants.go`.

**Comment by rainest** [comment]
At least in the context of KIC, review of items that I saw repeated PUTs for shows these fields at fault. [frequent.diff.txt](https://github.com/Kong/deck/files/6312980/frequent.diff.txt) has the full context:

```
updating upstream echo.default.80.svc  {
-      "https_verify_certificate": true,
-      "type": "http",
-    "threshold": 0
 }

updating route helmgress.echogress.00  {
-  "request_buffering": true,
-  "response_buffering": true,
 }
```
Simply ignoring fields not present in the target may be a viable option that's (hopefully) more lightweight than looking up defaults and populating them, is simpler to maintain than the current constants.go approach, and should bypass the boolean issue. However, it's a significant change to what it means to apply configuration, since it means that the state of an omitted field is definitely unknown.

The state is currently halfway unknown (for lack of a better description) at present: the client (deck) doesn't know what it is, but it's always the Kong default, whereas explicitly ignoring these fields means that someone could modify their value and have that modification persist (AFAIK the PUTs that try to remove it currently will reset it to the Kong default).

**Comment by hbagdi** [comment]
> Simply ignoring fields not present in the target may be a viable option

I'm not sure if that is a viable option since it defeats the "declarative" aspect of the project.

> The state is currently halfway unknown (for lack of a better description) at present: the client (deck) doesn't know what it is, but it's always the Kong default

And so we should make decK aware of the missing state. The more I think about it, I'm convinced that #89 is the way to go forward. If a user upgrades Kong and the upgrade introduces a few default properties, decK reports them as missing, next user goes ahead and adds the following to their state once:
```yaml
_defaults:
  route:
    request_buffering: true
```

And that gets rid off all the diffs for that specific properties.
Now, can we do better? I think yes. decK can automatically figure out which properties have a default and suppress those diffs. If there is a feasible way of parsing the schema that Kong provides, we can do that.

**Comment by GGabriele** [comment]
This has been supported since 1.11.0
