### ISSUE TITLE
deck sync --config no such file or directory

### ISSUE THREAD

**Issue by FieteO** [Kong/deck#230]
I am not able to point to a config file that lies in another directory.

**Steps to reproduce:**
Working in the same directory:  
``` bash
~$ deck dump
~$ deck sync
Summary:
  Created: 0
  Updated: 0
  Deleted: 0
```
Invoking from subdirectory:
``` bash
~$ mkdir subfolder
~$ cd subfolder
~/subfolder$ deck sync --config ../kong.yaml  
Error: reading state file: stat kong.yaml: no such file or directory
~/subfolder$ deck sync --config ~/subfolder/kong.yaml  
open /home/ubuntu/subfolder/kong.yaml: no such file or directory  
Error: reading state file: stat kong.yaml: no such file or directory
```
I have also tried to wrap the paths in double quotes with the same effect.
Am i using it wrong or is this an error?

**Comment by rainest** [comment]
You'll want to use `-s`. From `deck sync --help`:

> -s, --state strings                     file(s) containing Kong's configuration.

For example:

```
deck sync -s ~/subfolder/kong.yaml
```

`--config` is used for deck's configuration file, not the Kong configuration you want to sync (which we call the state file).

It looks like there may still be some issue with the file you're trying to use (the error is complaining that the file does not actually exist, rather than complaining that it's not a valid deck config file), but in either case, you still want to use `-s` to point to your saved Kong configuration.

I'll go ahead and close this out since it looks like the issue was most likely just confusion between the two flags, but if you're still having issues using `-s`, please reopen it.
