### ISSUE TITLE
Deck always defaults to konnect.yaml instead of kong.yaml

### ISSUE THREAD

**Issue by cwurm** [Kong/deck#288]
With decK 1.5 the default Kong configuration file is `konnect.yaml` and no longer `kong.yaml`. Reading the code, I believe this is a mistake? The non-Konnect commands still have `kong.yaml` as the default, e.g. https://github.com/Kong/deck/blob/a640f10a2017d77eb7d88a283064a02427366017/cmd/dump.go#L152-L154

However, the same variable names are used in the Konnect commands, e.g. https://github.com/Kong/deck/blob/a640f10a2017d77eb7d88a283064a02427366017/cmd/konnect_dump.go#L80-L82

What I think is happening is that the first thing `StringVarP` does is set the variable to the default value in https://github.com/spf13/pflag/blob/85dd5c8bc61cfa382fecd072378089d4e856579d/string.go#L6-L9

And since the Konnect files are alphabetically after the non-Konnect files their default value will always overwrite the non-Konnect values during package initialization.

The different commands should probably just use different variables to avoid any crossover.

**Comment by rainest** [comment]
Particularly annoying for dump because of the way [the `--all-workspaces` sanity check](https://github.com/Kong/deck/blob/a640f10a2017d77eb7d88a283064a02427366017/cmd/dump.go#L74-L76) works. The value is `konnect` regardless of which command you're using, so it fails on 1.5:

```
$ ./deck14 dump --all-workspaces
$ ./deck15 dump --all-workspaces 
Error: output-file cannot be specified with --all-workspace flag
```
A temporary workaround for 1.5 is to explicitly specify the old default. Even though it's not used for the filenames, it allows the check to pass and continues on to create the workspace filenames normally:

```
$ ./deck15 dump --all-workspaces -o kong
```

**Comment by danielkocot** [comment]
I use deck a lot in CI/CD contexts. 
- For `validate` it has to be `kong.yaml`
- `diff` needs a `konnect.yaml`
- And `sync` needs a `kong.yaml` again

It would nice to have the opportunity to flag the name of config file on demand.
