### ISSUE TITLE
Deck dump command fails with mtls-auths 403 Forbidden issue

### ISSUE THREAD

**Issue by adarsh279** [Kong/deck#326]
I am using deck 1.6.0 version with the combination of Kong EE 2.3.2 Version and Cassandra 3.11.10.
I have downloaded the binary version of deck from here https://github.com/Kong/deck/releases/deck_1.6.0_linux_amd64.tar.gz
 to make use of deck commands. I have realizes that I need to expose my Kong admin port outside my docker network for deck to make a connection with Kong.

I could able to do 'deck ping' which works by showing me the Kong version. however, when I try to use 'deck dump' I am getting the below error,
Error : reading configuration from Kong: mtls-auths:HTTP status 403 (message : "Forbidden")

Would like to know if cassandra need to be exposed out for this to work or is this something else.

Honestly, couldn't find much help for deck related queries online. It would be helpful if someone could answer the above. Thanks.

**Comment by rainest** [comment]
This happens when an Enterprise image is running in free mode (without a license). decK doesn't handle the free mode mTLS credential API effectively in current versions.

We have [a fix for this](https://github.com/Kong/deck/pull/321) staged for release. It will be available in 1.7, though I don't yet know when we plan to release that version.
