### ISSUE TITLE
deck ping returns bad version number

### ISSUE THREAD

**Issue by Tieske** [Kong/deck#361]
I have Kong Enterprise 2.3.3.1 running. 

```shell
$ deck ping
Successfully connected to Kong!
Kong version:  2.3.0
$
```

**Comment by rainest** [comment]
Per #363 this happens because we need to sanitize version strings to clear out non-semver stuff for version-specific functionality. We should split out that (which we use to gate version-specific functionality) from ping's reporting, which will be easier to do pending some other changes in upstream libraries.

**Comment by Tieske** [comment]
Not sure I get it. The Kong versions are not semver, so why parse it as one?

**Comment by hbagdi** [comment]
7d3c9fa6 should fix this issue as the code no-longer parses the version returned from Kong.
Please re-open if this issue persists with decK v1.7 (will be released soon).
