### ISSUE TITLE
Intermittent 502 errors "<failed to parse response body: invalid character '<' looking for beginning of value>"

### ISSUE THREAD

**Issue by cal5barton** [Kong/deck#526]
When running `deck diff ` or `deck sync` in our ci/cd pipeline we are getting intermittent 502 errors. We have to continue to re-run the job and eventually it will succeed. It doesn't seem to be consistent at all with any particular route or service. Any idea what could be going on or best way to resolve such behavior?

Example Deck Errors:
```
decK v1.8.2 (b538f70) 
RUNNING PING CMD....
Successfully connected to Kong!
Kong version:  2.6.0.0-enterprise-edition
RUNNING VALIDATE CMD...
RUNNING DIFF CMD...
Error: upstreams: HTTP status 502 (message: "<failed to parse response body: invalid character '<' looking for beginning of value>")
```

**Comment by d19dotca** [comment]
I see you opened up support case #00024998. We will continue the discussion there for now and report back here when we have a solution. At the moment, per the case notes, we believe this to be an ELB issue or something sitting in between decK and Kong Gateway, typically a mismatch in content-type too (application/json vs text/html).

**Comment by rainest** [comment]
The current retry logic only retries on 500s: https://github.com/Kong/deck/pull/226/files#diff-9b5d2fa5162a9c23e7b0c96446b28d54aa4c6676a697d2eb26073a5a76db602fR405-R417

As noted, the 502 likely isn't coming from Kong itself, since the admin API doesn't proxy to anywhere and shouldn't return 502s. We don't properly handle the non-JSON content type, but there's not much we could do there other than make the error handling cleaner.

Whether we should retry in this or really any scenario seems a bit of an open question: I'm not sure deck is fully idempotent internally (though AFAIK most resources do use PUT or DELETE exclusively).

IMO it seems like we'd want to defer to whatever's running deck and let it initiate the retry so that deck can confirm the current state again (or have deck restart higher up in the reconciliation process) in the event that a request received an error, but still succeeded (even though we did accept #226 as-is, retrying within the sync operation).

**Comment by GGabriele** [comment]
Closing this. Feel free to reopen or comment back if needed.
