### ISSUE TITLE
Windows 10 firewall says deck has trojan inside

### ISSUE THREAD

**Issue by duylddev** [Kong/deck#879]
I download decK from release page: https://github.com/Kong/deck/releases
and try to run on windows 10 but windows say decK has trojan inside

![image](https://user-images.githubusercontent.com/9783862/229222353-812bdf92-c5fd-472e-8341-9262100505de.png)

Please advise

**Comment by rainest** [comment]
There's not much insight we can provide here, since we don't have a view into their virus definitions.

I have submitted the executable to Microsoft's [threat intelligence submissions](https://www.microsoft.com/en-us/wdsi/filesubmission) for review, but at present the Windows 10 scanner is not picking up any issues:

![msi](https://user-images.githubusercontent.com/571832/231258675-c998df0c-b283-4885-a191-8d4fff482503.png)

Their [encyclopedia entry for the detected threat](https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?Name=Trojan:Win32/Sabsik.TE.A!ml) does not provide additional details about the malware's behavior--I don't know if it's maybe capable of replacing or modifying other executables on the machine, which could explain the discrepancy.

I'll go ahead and close this since a lack of detection in the cloud scanner means that Microsoft will probably just confirm that there is no detection when they process the report, but will keep this report in mind in case we see others.
